FROM node:16-alpine3.14

WORKDIR /usr/app

COPY package*.json ./
COPY tsconfig*.json ./

RUN npm install

COPY . ./

RUN npm run build

RUN mkdir -p ./build/utils/assets

COPY ./src/utils/assets/ ./build/utils/assets

CMD ["build/app.js"]